### ISSUE TITLE
Styling Refactor

### ISSUE THREAD

**Issue by glaciyan** [glaciyan/Lagersystem-Frontend#44]
- [x] Move Colors into css
- [ ] Convert the Button into variants and colors using less
- [ ] JavaScript controlled theme
- [ ] ThemeProvider Component

```less
@import '../themes/_variables.less';

.btn {
  border-radius: 0.375rem;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  font-weight: 600;
  cursor: pointer;
  transition: background-color 0.3s, color 0.3s;

  &.btn-solid {
    background-color: var(--btn-normal-color);
    color: var(--btn-text-normal-color);

    &:hover {
      background-color: var(--btn-hover-color);
      color: var(--btn-text-hover-color);
    }

    &:active {
      background-color: var(--btn-pressed-color);
    }
  }

  &.btn-outlined {
    background-color: transparent;
    color: var(--btn-text-outlined-color);
    border: 1px solid var(--btn-outlined-normal-color);

    &:hover {
      color: var(--btn-hover-color);
      border-color: var(--btn-hover-color);
    }

    &:active {
      color: var(--btn-pressed-color);
      border-color: var(--btn-pressed-color);
    }
  }

  &.btn-loading {
    background-color: var(--btn-loading-color);
    cursor: not-allowed;
  }

  &:disabled {
    background-color: var(--btn-disabled-color);
    color: var(--btn-disabled-text-color);
    cursor: not-allowed;
  }
}

```
